#!/usr/bin/env python3
"""Determine the type of macOS app."""

# standard libraries
import logging
import os
import plistlib
from pathlib import Path

# third party libraries
from macholib import MachO, mach_o

# Setup logging.
logging.basicConfig(
    filename="fub.log",
    filemode="w",
    format="%(asctime)s|%(name)s|%(levelname)s|%(message)s",
    level="INFO",
)


def get_arch(mac_app):
    """Determine the type of macOS app."""
    m = MachO.MachO(mac_app)
    archs = []
    for header in m.headers:
        cpu_type = header.header.cputype
        arch = str(mach_o.CPU_TYPE_NAMES.get(cpu_type)).lower()
        archs.append(arch)
    return archs


def print_list(items, header):
    """Print list with provided header."""
    print(header)
    for item in items:
        print(item)
    print()


def filter_binaries(mac_apps):
    """Determine the type of macOS app."""
    intel_binaries = []
    apple_binaries = []
    universal_binaries = []
    for mac_app in mac_apps:
        m = MachO.MachO(mac_app)
        archs = []
        for header in m.headers:
            cpu_type = header.header.cputype
            arch = str(mach_o.CPU_TYPE_NAMES.get(cpu_type)).lower()
            archs.append(arch)
        if "x86_64" in archs and "arm64" in archs:
            universal_binaries.append(str(mac_app))
        elif archs[0] == "x86_64":
            intel_binaries.append(str(mac_app))
        elif archs[0] == "arm64":
            apple_binaries.append(str(mac_app))

    print_list(intel_binaries, "Intel Binaries")
    print_list(apple_binaries, "Apple Binaries")
    print_list(universal_binaries, "Universal Binaries")


def get_app_binaries():
    """Get list of installed macOS applications."""
    apps = os.listdir("/Applications")
    apps.sort()
    binaries = []
    for app in apps:
        try:
            app_plist = Path("/Applications/" + app + "/Contents/Info.plist")
            with open(app_plist, "rb") as f:
                plist_data = plistlib.load(f)
            app_exe = plist_data["CFBundleExecutable"]
            mac_binary = Path("/Applications/" + app + "/Contents/MacOS/" + app_exe)
            binaries.append(mac_binary)
        except FileNotFoundError as e:
            logging.error(e)
        except NotADirectoryError as e:
            logging.error(e)

    return binaries


if __name__ == "__main__":
    # for binary in get_app_binaries():
    #     print(binary, end=" -> ")
    #     print(get_arch(binary))

    filter_binaries(get_app_binaries())
